package cn.inrhor.imipetcore.common.hook.protocol

import org.bukkit.entity.EntityType

object ProtocolEntity {

    // 1.8-1.12 只需要EntityType.typeId

    /**
     * 1.13-1.16.5 ProtocolLib 实体类型 对应 实体序号
     *
     * https://wiki.vg/index.php?title=Entity_metadata&oldid=16539
     */
    private val entityMap1 = mapOf(
        EntityType.BAT to 3,
        EntityType.BEE to 4,
        EntityType.BLAZE to 5,
        EntityType.CAT to 7,
        EntityType.CAVE_SPIDER to 8,
        EntityType.CHICKEN to 9,
        EntityType.COD to 10,
        EntityType.COW to 11,
        EntityType.CREEPER to 12,
        EntityType.DOLPHIN to 13,
        EntityType.DONKEY to 14,
        EntityType.DROWNED to 16,
        EntityType.ELDER_GUARDIAN to 17,
        EntityType.ENDER_DRAGON to 19,
        EntityType.ENDERMAN to 20,
        EntityType.ENDERMITE to 21,
        EntityType.EVOKER to 22,
        EntityType.EVOKER_FANGS to 23,
        EntityType.FOX to 28,
        EntityType.GHAST to 29,
        EntityType.GIANT to 30,
        EntityType.GUARDIAN to 31,
        EntityType.HOGLIN to 32,
        EntityType.HORSE to 33,
        EntityType.HUSK to 34,
        EntityType.ILLUSIONER to 35,
        EntityType.IRON_GOLEM to 36,
        EntityType.LLAMA to 42,
        EntityType.MAGMA_CUBE to 44,
        EntityType.MULE to 52,
        EntityType.MUSHROOM_COW to 53,
        EntityType.OCELOT to 54,
        EntityType.PANDA to 56,
        EntityType.PARROT to 57,
        EntityType.PHANTOM to 58,
        EntityType.PIG to 59,
        EntityType.PIGLIN to 60,
        EntityType.PIGLIN_BRUTE to 61,
        EntityType.PILLAGER to 62,
        EntityType.POLAR_BEAR to 63,
        EntityType.PUFFERFISH to 65,
        EntityType.RABBIT to 66,
        EntityType.RAVAGER to 67,
        EntityType.SALMON to 68,
        EntityType.SHEEP to 69,
        EntityType.SHULKER to 70,
        EntityType.SILVERFISH to 72,
        EntityType.SKELETON to 73,
        EntityType.SKELETON_HORSE to 74,
        EntityType.SLIME to 75,
        EntityType.SNOWMAN to 77,
        EntityType.SPIDER to 80,
        EntityType.SQUID to 81,
        EntityType.STRAY to 82,
        EntityType.STRIDER to 83,
        EntityType.TRADER_LLAMA to 89,
        EntityType.TROPICAL_FISH to 90,
        EntityType.TURTLE to 91,
        EntityType.VEX to 92,
        EntityType.VILLAGER to 93,
        EntityType.VINDICATOR to 94,
        EntityType.WANDERING_TRADER to 95,
        EntityType.WITCH to 96,
        EntityType.WITHER to 97,
        EntityType.WITHER_SKELETON to 98,
        EntityType.WOLF to 100,
        EntityType.ZOGLIN to 101,
        EntityType.ZOMBIE to 102,
        EntityType.ZOMBIE_HORSE to 103,
        EntityType.ZOMBIE_VILLAGER to 104,
        EntityType.ZOMBIFIED_PIGLIN to 105,
    )

    /**
     * 1.7-1.19.3 ProtocolLib 实体类型 对应 实体序号
     *
     * https://wiki.vg/Entity_metadata#Mobs
     */
    val entityMap2 = mapOf(
        EntityType.AXOLOTL to 4,
        EntityType.BAT to 5,
        EntityType.BEE to 6,
        EntityType.BLAZE to 7,
        EntityType.CAT to 10,
        EntityType.CAVE_SPIDER to 11,
        EntityType.CHICKEN to 12,
        EntityType.COD to 13,
        EntityType.COW to 14,
        EntityType.CREEPER to 15,
        EntityType.DOLPHIN to 16,
        EntityType.DONKEY to 17,
        EntityType.DROWNED to 19,
        EntityType.ELDER_GUARDIAN to 20,
        EntityType.ENDER_DRAGON to 22,
        EntityType.ENDERMAN to 23,
        EntityType.ENDERMITE to 24,
        EntityType.EVOKER to 25,
        EntityType.EVOKER_FANGS to 26,
        EntityType.FOX to 31,
        EntityType.FROG to 32,
        EntityType.GHAST to 33,
        EntityType.GIANT to 34,
        EntityType.GLOW_SQUID to 36,
        EntityType.GOAT to 37,
        EntityType.GUARDIAN to 38,
        EntityType.HOGLIN to 39,
        EntityType.HORSE to 40,
        EntityType.HUSK to 41,
        EntityType.ILLUSIONER to 42,
        EntityType.IRON_GOLEM to 43,
        EntityType.LLAMA to 49,
        EntityType.MAGMA_CUBE to 51,
        EntityType.MULE to 60,
        EntityType.MUSHROOM_COW to 61,
        EntityType.OCELOT to 62,
        EntityType.PANDA to 64,
        EntityType.PARROT to 65,
        EntityType.PHANTOM to 66,
        EntityType.PIG to 67,
        EntityType.PIGLIN to 68,
        EntityType.PIGLIN_BRUTE to 69,
        EntityType.PILLAGER to 70,
        EntityType.POLAR_BEAR to 71,
        EntityType.PUFFERFISH to 73,
        EntityType.RABBIT to 74,
        EntityType.RAVAGER to 75,
        EntityType.SALMON to 76,
        EntityType.SHEEP to 77,
        EntityType.SHULKER to 78,
        EntityType.SILVERFISH to 80,
        EntityType.SKELETON to 81,
        EntityType.SKELETON_HORSE to 82,
        EntityType.SLIME to 83,
        EntityType.SNOWMAN to 85,
        EntityType.SPIDER to 88,
        EntityType.SQUID to 89,
        EntityType.STRAY to 90,
        EntityType.STRIDER to 91,
        EntityType.TADPOLE to 92,
        EntityType.TRADER_LLAMA to 98,
        EntityType.TROPICAL_FISH to 99,
        EntityType.TURTLE to 100,
        EntityType.VEX to 101,
        EntityType.VILLAGER to 102,
        EntityType.VINDICATOR to 103,
        EntityType.WANDERING_TRADER to 104,
        EntityType.WARDEN to 105,
        EntityType.WITCH to 106,
        EntityType.WITHER to 107,
        EntityType.WITHER_SKELETON to 108,
        EntityType.WOLF to 110,
        EntityType.ZOGLIN to 111,
        EntityType.ZOMBIE to 112,
        EntityType.ZOMBIE_HORSE to 113,
        EntityType.ZOMBIE_VILLAGER to 114,
        EntityType.ZOMBIFIED_PIGLIN to 115,
    )

}