# 数据存储
data:
  # 存储类型 YAML MYSQL
  type: YAML
  host: localhost
  port: 3306
  user: root
  password: root
  database: imipetcore
  table: imipetcore_table

nms: taboolib

# 调式信息模式
debug: false

# 启动服务器时清理操作
clear:
  # true则启动服务器后清理残留的宠物实体
  # 有时候在未正常关闭服务器时残留实体
  entity: false